### ISSUE TITLE
Animations not displayed in notebook on Github

### ISSUE THREAD

**Issue by inakleinbottle** [datasig-ac-uk/signature_applications#2]
The animations do not seem to be rendered in the notebook, possibly due to the size of the resulting image files. Is there anything that can be done to reduce the resolution or something to reduce the size of the animation files cached inside the notebook so they are properly displayed on Github?

**Comment by pafoster** [comment]
@inakleinbottle Animations not displaying might due to a limitation of the static HTML rendering used in Github, which is more limited compared to Jupyter. In the action recognition notebooks, we use moviepy to display an HTML5 control to play back an AVI file -- it's not clear to me whether the Github rendering supports the display of the control and/or if this is related to file size. A work-around might be to display an animated gif, but that would potentially come with a loss of ability to control playback. To reduce the friction associated with running the notebook, another option might be to explore the possibility of using [Binder](https://mybinder.org/).

**Comment by inakleinbottle** [comment]
@pafoster This was my conclusion too. Github does render GIFs. Perhaps there is a way to store the animations as GIFs inside the notebook so they are rendered in Github?
